### ISSUE TITLE
invalid version unknown revision mentioned in log when we want to update the module

### ISSUE THREAD

**Issue by hang-ren** [clusterpedia-io/clusterpedia#183] opened 2022-05-19 02:04 UTC
### What happened?

In our project, we required this module like this:

github.com/clusterpedia-io/api v0.0.0-20220510034551-b353c251711d

But we found that it will show invalid version error when we try to check/show it:
<img width="861" alt="企业微信截图_e0e3e3ab-66da-46d7-83a8-dd8428ca2b9b" src="https://user-images.githubusercontent.com/29770618/169187668-0c4f8881-39c4-468c-b004-18eb38ce2df7.png">

And I check it in the repo, found it is true that the branch/tag was not existing:
<img width="849" alt="企业微信截图_93a7ae82-2d83-4615-9ca0-f9fcaf6a4974" src="https://user-images.githubusercontent.com/29770618/169187871-6c8f6442-10cf-4a35-a095-e8cbefc95359.png">

So could you please have a check with it, I am afraid that we can't use this module with the latest version.
 

### What did you expect to happen?

Need an available version which can be required.

### How can we reproduce it (as minimally and precisely as possible)?

Please see the screenshot and description.

### Clusterpedia Version

github.com/clusterpedia-io/api v0.0.0-20220510034551-b353c251711d

### Host Kubernetes version

None

**Comment by Iceber** [comment] 2022-05-19 03:25
This is an issue caused by the first push of the [repository](https://github.com/clusterpedia-io/client-go) and may require a specific `api` version to be specified for the time being.
```
github.com/clusterpedia-io/api v0.0.0-20220507025304-d012b86e5587
```


This will be fixed automatically the next time the api changes

**Comment by calvin0327** [comment] 2022-05-28 08:30
The issue has be solved. it can be closed. @Iceber

**Comment by Iceber** [comment] 2022-05-30 04:27
@calvin0327 The version order looks the same as before
https://pkg.go.dev/github.com/clusterpedia-io/api?tab=versions

**Comment by Iceber** [comment] 2022-05-30 04:38
The [staging/api](https://github.com/clusterpedia-io/clusterpedia/tree/main/staging/src/github.com/clusterpedia-io/api) has been updated and the problem is fixed after syncing to the api

**Comment by Iceber** [comment] 2022-06-06 02:55
[clusterpedia-io/api](https://github.com/clusterpedia-io/api) has been updated

**Closed by Iceber** 2022-06-06 02:55 UTC
Labels: kind/bug
